
# Change summary
# - Generated by atom-package-generator
# - Left the generated code as-is, since the default is useful enough.

LanguageZvmNamesView = require './language-zvm-names-view'
{CompositeDisposable} = require 'atom'

module.exports = LanguageZvmNames =
  languageZvmNamesView: null
  modalPanel: null
  subscriptions: null

  activate: (state) ->
    @languageZvmNamesView = new LanguageZvmNamesView(state.languageZvmNamesViewState)
    @modalPanel = atom.workspace.addModalPanel(item: @languageZvmNamesView.getElement(), visible: false)

    # Events subscribed to in atom's system can be easily cleaned up with a CompositeDisposable
    @subscriptions = new CompositeDisposable

    # Register command that toggles this view
    @subscriptions.add atom.commands.add 'atom-workspace', 'language-zvm-names:toggle': => @toggle()

  deactivate: ->
    @modalPanel.destroy()
    @subscriptions.dispose()
    @languageZvmNamesView.destroy()

  serialize: ->
    languageZvmNamesViewState: @languageZvmNamesView.serialize()

  toggle: ->
    console.log 'LanguageZvmNames was toggled!'

    if @modalPanel.isVisible()
      @modalPanel.hide()
    else
      @modalPanel.show()
