
# Change summary
# - Generated by atom-package-generator
# - Left the generated code as-is, since the default is useful enough.

LanguageZvmNamesView = require '../lib/language-zvm-names-view'

describe "LanguageZvmNamesView", ->
  it "has one valid test", ->
    expect("life").toBe "easy"
